
spring:
    datasource:

        url: jdbc:mysql://127.0.0.1:3306/sq_yiqing_db?serverTimezone=GMT%2B8&characterEncoding=utf8
        username: root
        password: 123123
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    typeAliasesPackage: com.example.demo.sq.entity
    mapperLocations: classpath:mapper/*.xml

logging:
    level:
        com.example.demo.sq.mappers: debug
